### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by Ciberusps** [OrchidIsle/UE5-Build-Project#18]
Runned workflow without plugin - all works fine

Cloned my plugin to "Plugins" folder and get error 
```
"Error: Plugin 'UnrealHelperLibrary' failed to load because module 'UnrealHelperLibrary' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project"
```
![image](https://github.com/user-attachments/assets/d18e62e9-5323-4257-81cd-d30af1168e0c)

Tried to run checkouted project by hands 
![image](https://github.com/user-attachments/assets/052d0ec3-1389-4bef-9616-69eb77a90739)
And all works fine project runs after "Yes" in this window
![image](https://github.com/user-attachments/assets/205d8706-ad12-45b5-97de-c1e68a2c0307)

Looks like plugins should be build with `UAT` before building project?
https://dev.epicgames.com/community/learning/tutorials/qz93/unreal-engine-building-plugins

**Comment by edwardteach42** [comment]
The only time I ran into that issue was when my Github runner was failing to properly clone my submodules (in my case, plugins) into my project.  Here are the first steps that I use on a build:

```
jobs:
  build:
    runs-on: self-hosted
    environment: ${{ 
        (github.ref == 'refs/heads/dev' && 'Development') || 
        (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-alpha') && 'Staging') || 
        (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-beta') && 'Staging') || 
        (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/') && contains(github.ref, '-rc') && 'Staging') || 
        (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/') && 'Production') || 
        'Development' 
      }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        lfs: true
        fetch-depth: 0 # Fetches all history for all tags and branches
        submodules: recursive

    - name: Checkout LFS Objects
      run: git lfs checkout
```
I will test with Unreal Helper Library myself later to try and trace the issue.

**Comment by Ciberusps** [comment]
Do you store your plugins compiled with "Intermediate"/"DerivedDataCache"/"Saved"?

**Comment by Ciberusps** [comment]
Its important to note that I use "Blueprint" project, it builds fine without plugin(s)
https://github.com/Ciberusps/UE_5_4_Blueprint

UPD my `github-action` setup
```
name: Test

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out UE5.4 project
        uses: actions/checkout@v3
        with:
          repository: Ciberusps/UE_5_4_Blueprint
          path: UE_5_4_Blueprint
      
      - name: Check out UnrealHelperLibrary to Plugins folder
        uses: actions/checkout@v3
        with:
          path: UE_5_4_Blueprint/Plugins/UnrealHelperLibrary
	    
      # - name: Build Plugins (UHL)
      #   shell: powershell
      #   run: |
      #     mkdir "Temp"
      #     $pluginPath = Resolve-Path -Path "UE_5_4_Blueprint/Plugins/UnrealHelperLibrary/UnrealHelperLibrary.uplugin"
      #     $tempDirAbsolutePath = Resolve-Path -Path "Temp"
      #     "S:/Epic Games/UE_5.4/Engine/Build/BatchFiles/RunUAT.bat BuildPlugin -plugin="$pluginPath" -package="$tempDirAbsolutePath""

      - name: Build project
        uses: OrchidIsle/UE5-Build-Project@latest
        with:
          RUNUAT_PATH: 'S:/Epic Games/UE_5.4/Engine/Build/BatchFiles/RunUAT.bat'
          UPROJECT_PATH: ${{ github.workspace }}/UE_5_4_Blueprint/UE_5_4_Blueprint.uproject
          BUILD_CONFIG: Development
          PLATFORM: Win64
          CLEAN: true
          COOK: true
          STAGE: true
          PACKAGE: true
          PAK: true
          SERVER: false
          ARCHIVE: false
          ARCHIVE_PATH: 'C:/Archives/MyGame'
          NULLRHI: true
          EDITOR: true
          ENCRYPT_INI: true
          # RELEASE: '1.0.0'
          # PATCH: '0.9.0'
          # MAPS: 'Map1,Map2'
          DELETE_PDB: true
          # ANTICHEAT_ENABLED: true
          # ANTICHEAT_PRIVATE_KEY: 'base64encodedprivatekey'
          # ANTICHEAT_PUBLIC_CERT: 'base64encodedpubliccert'
```
